version: '3'
volumes: 
    dados:
services: 
    mysql:
        image: mysql
        container_name: mysql
        ports:
            - 3306:3306
        networks:
            - hospital-network
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: 'hospital_api'
        volumes:
            - dados:/var/lib/mysql

    # nginx: 
    #     image: nginx:latest
    #     container_name: nginx        
    #     ports:
    #         - 8080:80
    #     networks: 
    #         hospital-network:
    #             ipv4_address: 172.19.0.7
    #     volumes:
    #         - ./server:/code
    #         - ./docker/config/nginx.conf:/etc/nginx/conf.d/default.conf
    #     links:
    #         - slim
    #     depends_on:
    #         - slim

    front:
        image: node
        container_name: front
        networks:
            hospital-network:
                ipv4_address: 172.19.0.6
        ports:
            - 80:8080
        depends_on:
             - slim
        working_dir: /app
        volumes:
            - ./client:/app
            - ./config:/config
        command: bash -c "npm i && npm start"
    
    slim:
        image: gustavosoares97/php-pdo
        container_name: slim
        working_dir: /var/www
        command: bash -c "composer db-update && composer start"
        environment:
            docker: "true"
        ports:
            - 3001:3001
        networks:
            hospital-network:
                ipv4_address: 172.19.0.8
        depends_on:
            - mysql
        volumes:
            - ./server:/var/www
            - ./server/logs:/var/www/logs
            - ./config:/var/config
    
networks: 
    hospital-network:
        driver: bridge
        ipam:
         config:
           - subnet: 172.19.0.0/16
