#DESENVOLVIMENTO ===========================================================
DEVELOPER:
    HOST: 'localhost'
    DOMAIN: dev
    
    DATABASE_NAME: 'hospital_api'

    DB_BOOTSTRAP_HOST: 'mysql'
    DB_BOOTSTRAP_USER: 'root'
    DB_BOOTSTRAP_PASSWORD: 'root'
    DB_BOOTSTRAP_DRIVER: 'pdo_mysql'

    DB_APPLICATION_HOST: 'mysql'
    DB_APPLICATION_USER: 'root'
    DB_APPLICATION_PASSWORD: 'root'
    DB_APPLICATION_DRIVER: 'pdo_mysql'

    ACTIVE_DIRECORY: NULL

    DEBUG_ACTIVE: true
    DEBUG_EMAIL: 'gustavo.soares@gampcanoas.com.br'
HOMOLOG:
    
#HOMOLOGAÇÃO ===============================================================
    HOST: '10.100.200.100'
    DOMAIN: homo
    
    DATABASE_NAME: 'intra2_homolog'
    
    DB_BOOTSTRAP_HOST: '10.100.1.33'
    DB_BOOTSTRAP_USER: 'dev'
    DB_BOOTSTRAP_PASSWORD: 'devloop356'
    DB_BOOTSTRAP_DRIVER: 'pdo_mysql'

    DB_APPLICATION_HOST: '10.100.1.33'
    DB_APPLICATION_USER: 'homo'
    DB_APPLICATION_PASSWORD: 'homolog123'
    DB_APPLICATION_DRIVER: 'pdo_mysql'

    AD_HOST: '10.100.1.10'
    AD_USER: 'servweb'
    AD_PASSWORD: 'hu@esc@gamp@web'
    AD_DOMAIN: '@hmd.local'
    
    DEBUG_ACTIVE: true
    DEBUG_EMAIL: 'gustavo.soares@gampcanoas.com.br'

#PRODUÇÃO ==================================================================
PRODUCTION:
    HOST: '10.100.1.32'
    DOMAIN: prod
    
    DATABASE_NAME: 'intra2'
        
    DB_BOOTSTRAP_HOST: '10.100.1.33'
    DB_BOOTSTRAP_USER: 'dev'
    DB_BOOTSTRAP_PASSWORD: 'devloop356'
    DB_BOOTSTRAP_DRIVER: 'pdo_mysql'

    DB_APPLICATION_HOST: '10.100.1.33'
    DB_APPLICATION_USER: 'prod'
    DB_APPLICATION_PASSWORD: 'prod362'
    DB_APPLICATION_DRIVER: 'pdo_mysql'

    AD_HOST: '10.100.1.10'
    AD_USER: 'servweb'
    AD_PASSWORD: 'hu@esc@gamp@web'
    AD_DOMAIN: '@hmd.local'
    
    DEBUG_ACTIVE: true
    DEBUG_EMAIL: 'gustavo.soares@gampcanoas.com.br'

